#include "suns/production.hpp"
#include "suns/terraforming.hpp"
#include "suns/campaign.hpp"

#include <algorithm>
#include <cctype>
#include <numeric>
#include <type_traits>

namespace suns {

bool production_batch_valid(const QueueProductionBatchOrder& order)
{
    if (order.quantity == 0 || order.quantity > kMaximumProductionBatch) return false;
    if (order.kind != ProductionKind::Factory && order.kind != ProductionKind::Mine
        && order.kind != ProductionKind::Terraforming) return false;
    if (static_cast<unsigned>(order.automation) > static_cast<unsigned>(ProductionAutomation::MaxTerraform)) return false;
    if (order.kind == ProductionKind::Terraforming) return order.automation != ProductionAutomation::Annual;
    return order.automation == ProductionAutomation::None || order.automation == ProductionAutomation::Annual;
}

bool apply_production_batch(const GameState& state, Planet& planet, const QueueProductionBatchOrder& order)
{
    if (planet.id != order.colony || !production_batch_valid(order)) return false;
    if (order.kind == ProductionKind::Terraforming
        && !next_terraforming_environment(state, planet.owner, planet)) return false;
    planet.productionQueue.push_back({order.kind, production_cost(order.kind), 0,
        order.automation, order.quantity});
    return true;
}

bool production_template_valid(const ProductionTemplate& value)
{
    if (value.name.empty() || value.name.size() > 80 || value.items.empty() || value.items.size() > 64
        || std::none_of(value.name.begin(), value.name.end(), [](unsigned char c) { return !std::isspace(c); })) return false;
    return std::all_of(value.items.begin(), value.items.end(), [](const ProductionItem& item) {
        return item.automation != ProductionAutomation::None && !item.autoGenerated && item.shipDesign == 0
            && item.remainingCost == production_cost(item.kind)
            && production_batch_valid({0, item.kind, item.quantity, item.automation});
    });
}

bool set_production_template(Player& player, const SetProductionTemplateOrder& order)
{
    auto found = std::find_if(player.productionTemplates.begin(), player.productionTemplates.end(),
        [&](const auto& value) { return value.name == order.value.name; });
    if (order.remove) {
        if (found == player.productionTemplates.end()) return false;
        player.productionTemplates.erase(found);
        return true;
    }
    if (!production_template_valid(order.value)
        || (found == player.productionTemplates.end() && player.productionTemplates.size() >= 16)) return false;
    if (order.value.defaultForNewColonies)
        for (auto& value : player.productionTemplates) value.defaultForNewColonies = false;
    if (found == player.productionTemplates.end()) player.productionTemplates.push_back(order.value);
    else *found = order.value;
    return true;
}

bool apply_production_template(Planet& planet, const Player& player, const std::string& name)
{
    if (planet.owner != player.id) return false;
    const auto found = std::find_if(player.productionTemplates.begin(), player.productionTemplates.end(),
        [&](const auto& value) { return value.name == name; });
    if (found == player.productionTemplates.end() || !production_template_valid(*found)) return false;
    std::erase_if(planet.productionQueue, [](const auto& item) { return item.automation != ProductionAutomation::None; });
    planet.productionQueue.insert(planet.productionQueue.end(), found->items.begin(), found->items.end());
    return true;
}

void apply_default_production_template(const GameState& state, Planet& planet)
{
    const auto* player = find_player(state, planet.owner);
    if (!player) return;
    const auto found = std::find_if(player->productionTemplates.begin(), player->productionTemplates.end(),
        [](const auto& value) { return value.defaultForNewColonies; });
    if (found != player->productionTemplates.end()) (void)apply_production_template(planet, *player, found->name);
}

ColonyProductionResolution resolve_colony_production(const GameState& state, Planet& planet, bool hasShipyard)
{
    ColonyProductionResolution result;
    result.hasShipyard = hasShipyard;
    if (planet.owner == 0) return result;
    const auto* player = find_player(state, planet.owner);
    const auto output = colony_output(planet);
    const bool researchActive = player && player->technology.researchActive;
    const auto allocated = researchActive ? static_cast<std::uint32_t>(
        std::uint64_t(output) * player->technology.researchAllocationPercent / 100U) : 0U;
    result.researchPoints = allocated;
    auto available = output - allocated;
    auto& queue = planet.productionQueue;
    std::vector<std::size_t> origins(queue.size());
    std::iota(origins.begin(), origins.end(), 0);
    std::vector<std::uint32_t> annualUsed(queue.size());
    planet.productionWaitingForMinerals = false;
    planet.productionWaitingForShipyard = false;
    bool stationExists = hasShipyard || find_orbital_station_at_planet(state, planet.id) != nullptr;
    const auto erase = [&](std::size_t index) {
        queue.erase(queue.begin() + index);
        origins.erase(origins.begin() + index);
    };
    const auto complete = [&](const ProductionItem& item, std::size_t origin, bool finishedBatch) {
        subtract_minerals(planet.minerals, production_item_mineral_cost(state, item));
        if (item.kind == ProductionKind::Factory) ++planet.industry;
        else if (item.kind == ProductionKind::Mine) ++planet.mines;
        else if (item.kind == ProductionKind::Terraforming) (void)terraform_planet(state, planet);
        else if (item.kind == ProductionKind::OrbitalStation) {
            stationExists = true;
            result.hasShipyard = true;
        }
        result.completions.push_back({item, origin, finishedBatch,
            item.kind == ProductionKind::Factory ? planet.industry : item.kind == ProductionKind::Mine ? planet.mines : 0U});
    };
    std::size_t index = 0;
    while (index < queue.size()) {
        const auto origin = origins[index];
        if (queue[index].kind == ProductionKind::Research || queue[index].quantity == 0
            || (queue[index].kind == ProductionKind::OrbitalStation && stationExists)) { erase(index); continue; }
        const auto kind = queue[index].kind;
        const bool automatic = queue[index].automation != ProductionAutomation::None;
        if (automatic) {
            const auto rule = queue[index];
            while (annualUsed[origin] < rule.quantity) {
                if (kind == ProductionKind::Terraforming
                    && ((rule.automation == ProductionAutomation::MinTerraform
                            && player_planet_habitability(state, planet.owner, planet, state.turn) >= 0)
                        || !next_terraforming_environment(state, planet.owner, planet))) break;
                ProductionItem work{kind, production_cost(kind), 0, ProductionAutomation::None, 1, true};
                // Auto rules cannot monopolize production while lacking minerals.
                if (!mineral_cargo_sufficient(planet.minerals, production_item_mineral_cost(state, work))) break;
                if (available == 0) break;
                const auto spent = std::min(available, work.remainingCost);
                work.remainingCost -= spent;
                available -= spent;
                if (work.remainingCost != 0) {
                    queue.insert(queue.begin() + index, work);
                    origins.insert(origins.begin() + index, origin);
                    ++index; // The unfinished normal build precedes its persistent rule.
                    break;
                }
                ++annualUsed[origin];
                complete(work, origin, false);
            }
            ++index;
            continue;
        }
        if (kind == ProductionKind::Terraforming && !next_terraforming_environment(state, planet.owner, planet)) {
            erase(index); // No eligible work remains: surplus manual terraforming is discarded without charge.
            continue;
        }
        if (kind == ProductionKind::ColonyShip && !result.hasShipyard) {
            planet.productionWaitingForShipyard = true;
            break;
        }
        const auto spent = std::min(available, queue[index].remainingCost);
        available -= spent;
        queue[index].remainingCost -= spent;
        if (queue[index].remainingCost != 0) break;
        if (!mineral_cargo_sufficient(planet.minerals, production_item_mineral_cost(state, queue[index]))) {
            planet.productionWaitingForMinerals = true;
            break;
        }
        const auto completed = queue[index];
        const bool finished = completed.quantity == 1;
        if (completed.autoGenerated && index + 1 < queue.size()
            && queue[index + 1].automation != ProductionAutomation::None && queue[index + 1].kind == kind)
            ++annualUsed[origins[index + 1]];
        complete(completed, origin, finished);
        if (finished) erase(index);
        else { --queue[index].quantity; queue[index].remainingCost = production_item_cost(state, queue[index]); }
    }
    if (researchActive) result.researchPoints += available;
    result.queueOrigins = std::move(origins);
    return result;
}

GameState planned_production_state(const GameState& state, const PlayerOrders& pending)
{
    auto result = planned_ship_design_state(state, pending);
    for (const auto& order : pending.orders) std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
        if constexpr (std::is_same_v<T, SetProductionTemplateOrder>) {
            const auto player = std::find_if(result.players.begin(), result.players.end(),
                [&](const auto& entry) { return entry.id == pending.player; });
            if (player != result.players.end()) (void)set_production_template(*player, value);
        } else if constexpr (std::is_same_v<T, QueueProductionBatchOrder> || std::is_same_v<T, ApplyProductionTemplateOrder>
            || std::is_same_v<T, QueueProductionOrder> || std::is_same_v<T, QueueShipDesignOrder>
            || std::is_same_v<T, ReorderProductionQueueOrder> || std::is_same_v<T, CancelProductionOrder>) {
            const auto found = std::find_if(result.planets.begin(), result.planets.end(),
                [&](const auto& entry) { return entry.id == value.colony && entry.owner == pending.player; });
            if (found == result.planets.end()) return;
            auto& colony = *found;
            std::erase_if(colony.productionQueue, [](const auto& item) { return item.kind == ProductionKind::Research; });
            auto& queue = colony.productionQueue;
            if constexpr (std::is_same_v<T, QueueProductionBatchOrder>) (void)apply_production_batch(result, colony, value);
            else if constexpr (std::is_same_v<T, ApplyProductionTemplateOrder>) {
                if (const auto* player = find_player(result, pending.player)) (void)apply_production_template(colony, *player, value.name);
            } else if constexpr (std::is_same_v<T, CancelProductionOrder>) {
                if (value.index < queue.size()) queue.erase(queue.begin() + value.index);
            } else if constexpr (std::is_same_v<T, ReorderProductionQueueOrder>) {
                if (value.fromIndex < queue.size() && value.toIndex < queue.size()) {
                    auto item = queue[value.fromIndex];
                    queue.erase(queue.begin() + value.fromIndex);
                    queue.insert(queue.begin() + value.toIndex, item);
                }
            } else if constexpr (std::is_same_v<T, QueueShipDesignOrder>) {
                if (const auto* design = resolve_ship_design_order(result, pending.player, value);
                    design && design->owner == pending.player && ship_design_valid(*design)
                    && colony_has_orbital_service(result, colony.id, pending.player, OrbitalStationModule::Shipyard))
                    queue.push_back({ProductionKind::ColonyShip, ship_design_cost(*design), design->id});
            } else if constexpr (std::is_same_v<T, QueueProductionOrder>) {
                if (value.kind == ProductionKind::Factory || value.kind == ProductionKind::Mine || value.kind == ProductionKind::Terraforming)
                    (void)apply_production_batch(result, colony, {colony.id, value.kind});
                else if (value.kind == ProductionKind::OrbitalStation && !find_orbital_station_at_planet(result, colony.id)
                    && std::none_of(queue.begin(), queue.end(), [](const auto& item) { return item.kind == ProductionKind::OrbitalStation; }))
                    queue.push_back({value.kind, kOrbitalDockCost});
                else if (value.kind == ProductionKind::ColonyShip
                    && colony_has_orbital_service(result, colony.id, pending.player, OrbitalStationModule::Shipyard)) {
                    const auto design = std::find_if(result.shipDesigns.begin(), result.shipDesigns.end(),
                        [&](const auto& candidate) { return candidate.owner == pending.player && ship_design_can_colonize(candidate); });
                    if (design != result.shipDesigns.end()) queue.push_back({value.kind, ship_design_cost(*design), design->id});
                }
            }
        }
    }, order);
    return result;
}

} // namespace suns
