#include "main_window.hpp"
#include "suns/production.hpp"
#include "suns/terraforming.hpp"
#include "suns/campaign.hpp"

#include <QDockWidget>
#include <QComboBox>
#include <QCheckBox>
#include <QLineEdit>
#include <QSpinBox>
#include <QSignalBlocker>
#include <QGroupBox>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QScrollBar>
#include <QSizePolicy>
#include <QShortcut>
#include <QTimer>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QVBoxLayout>

#include <algorithm>
#include <cstddef>
#include <type_traits>

namespace suns {
namespace {

QString mineralAmounts(const MineralCargo& minerals)
{
    return QString("I %1 / B %2 / G %3 kt")
        .arg(minerals.ironium, 0, 'f', 1).arg(minerals.boranium, 0, 'f', 1).arg(minerals.germanium, 0, 'f', 1);
}

QString productionItemName(const GameState& state, const ProductionItem& item)
{
    QString name;
    switch (item.kind) {
    case ProductionKind::Factory: name = "Factory"; break;
    case ProductionKind::Mine: name = "Mine"; break;
    case ProductionKind::Terraforming: name = "Terraforming"; break;
    case ProductionKind::Research: return "Legacy Research item";
    case ProductionKind::OrbitalStation: name = "Orbital Dock"; break;
    case ProductionKind::ColonyShip:
        if (const auto* design = find_ship_design(state, item.shipDesign != 0 ? item.shipDesign : kColonyShipDesignId))
            return QString::fromStdString(design->name);
        return "Ship";
    }
    if (item.automation != ProductionAutomation::None) {
        if (item.automation == ProductionAutomation::MinTerraform) name = "Min Terraform";
        if (item.automation == ProductionAutomation::MaxTerraform) name = "Max Terraform";
        return QString("↻ %1").arg(name);
    }
    if (item.quantity > 1) name += QString(" ×%1").arg(item.quantity);
    if (item.autoGenerated) name += " (in progress)";
    return name;
}

} // namespace

std::vector<ProductionItem> MainWindow::plannedProductionQueue(const Planet& planet) const
{
    const auto planned = planned_production_state(state_, pendingOrders_);
    const auto found = std::find_if(planned.planets.begin(), planned.planets.end(),
        [&](const auto& candidate) { return candidate.id == planet.id; });
    return found == planned.planets.end() ? std::vector<ProductionItem>{} : found->productionQueue;
}

void MainWindow::installProductionQueue()
{
    auto* dock = findChild<QDockWidget*>("productionDock");
    auto* panel = dock ? dock->widget() : nullptr;
    auto* panelLayout = panel ? qobject_cast<QVBoxLayout*>(panel->layout()) : nullptr;
    if (!panelLayout) return;

    auto* group = new QGroupBox("Build queue", panel);
    group->setObjectName("productionQueueGroup");
    auto* layout = new QVBoxLayout(group);

    auto* addRow = new QHBoxLayout;
    auto* kind = new QComboBox(group);
    kind->setObjectName("productionBatchKind");
    const auto addKind = [&](const char* label, ProductionKind item, ProductionAutomation automation) {
        kind->addItem(label, int(item));
        kind->setItemData(kind->count() - 1, int(automation), Qt::UserRole + 1);
    };
    addKind("Factories", ProductionKind::Factory, ProductionAutomation::None);
    addKind("Mines", ProductionKind::Mine, ProductionAutomation::None);
    addKind("Terraform", ProductionKind::Terraforming, ProductionAutomation::None);
    addKind("Auto factories ↻", ProductionKind::Factory, ProductionAutomation::Annual);
    addKind("Auto mines ↻", ProductionKind::Mine, ProductionAutomation::Annual);
    addKind("Min Terraform ↻", ProductionKind::Terraforming, ProductionAutomation::MinTerraform);
    addKind("Max Terraform ↻", ProductionKind::Terraforming, ProductionAutomation::MaxTerraform);
    auto* amount = new QSpinBox(group);
    amount->setObjectName("productionBatchQuantity");
    amount->setRange(1, int(kMaximumProductionBatch));
    amount->setValue(10);
    amount->setToolTip("Units to build once, or maximum units each year for an auto rule. Actual output depends on queue priority, production and minerals.");
    auto* add = new QPushButton("Add", group);
    add->setObjectName("productionBatchAdd");
    addRow->addWidget(kind, 1); addRow->addWidget(amount); addRow->addWidget(add);
    layout->addLayout(addRow);
    connect(kind, &QComboBox::currentIndexChanged, this, [this] { refreshProductionQueue(); });
    connect(add, &QPushButton::clicked, this, [this, kind, amount] {
        const auto* planet = selectedPlanet();
        if (!planet || planet->owner != pendingOrders_.player) return;
        const QueueProductionBatchOrder order{planet->id, ProductionKind(kind->currentData().toInt()),
            std::uint32_t(amount->value()), ProductionAutomation(kind->currentData(Qt::UserRole + 1).toInt())};
        if (!production_batch_valid(order)) return;
        appendPendingOrder(order, QString("Queue %1 ×%2 at %3").arg(kind->currentText()).arg(amount->value())
            .arg(QString::fromStdString(planet->name)));
        refreshProductionQueue();
    });
    auto* templateRow = new QHBoxLayout;
    auto* templates = new QComboBox(group);
    templates->setObjectName("productionTemplateName");
    templates->setEditable(true);
    templates->setInsertPolicy(QComboBox::NoInsert);
    templates->lineEdit()->setMaxLength(80);
    templates->lineEdit()->setPlaceholderText("Template name");
    auto* save = new QPushButton("Save", group);
    save->setObjectName("productionTemplateSave");
    save->setToolTip("Save the queue's persistent auto rules. One-off and partially completed builds are kept separately.");
    auto* apply = new QPushButton("Apply", group);
    apply->setObjectName("productionTemplateApply");
    apply->setToolTip("Replace this colony's auto rules; keep normal builds and append the selected template after them.");
    auto* remove = new QPushButton("Delete", group);
    remove->setObjectName("productionTemplateDelete");
    templateRow->addWidget(templates, 1); templateRow->addWidget(save); templateRow->addWidget(apply); templateRow->addWidget(remove);
    layout->addLayout(templateRow);
    auto* newColonies = new QCheckBox("Default for new colonies", group);
    newColonies->setObjectName("productionTemplateDefault");
    layout->addWidget(newColonies);
    connect(save, &QPushButton::clicked, this, [this, templates, newColonies] {
        const auto* planet = selectedPlanet();
        if (!planet || planet->owner != pendingOrders_.player) return;
        ProductionTemplate value{templates->currentText().trimmed().toStdString(), {}, newColonies->isChecked()};
        for (auto item : plannedProductionQueue(*planet)) if (item.automation != ProductionAutomation::None) {
            item.remainingCost = production_cost(item.kind);
            item.autoGenerated = false;
            value.items.push_back(item);
        }
        if (!production_template_valid(value)) return;
        appendPendingOrder(SetProductionTemplateOrder{value}, QString("Save production template %1").arg(templates->currentText()));
        refreshProductionQueue();
    });
    connect(apply, &QPushButton::clicked, this, [this, templates] {
        const auto* planet = selectedPlanet();
        if (!planet || planet->owner != pendingOrders_.player) return;
        appendPendingOrder(ApplyProductionTemplateOrder{planet->id, templates->currentText().toStdString()},
            QString("Apply production template %1").arg(templates->currentText()));
        refreshProductionQueue();
    });
    connect(remove, &QPushButton::clicked, this, [this, templates] {
        appendPendingOrder(SetProductionTemplateOrder{{templates->currentText().toStdString()}, true},
            QString("Delete production template %1").arg(templates->currentText()));
        refreshProductionQueue();
    });
    connect(templates, &QComboBox::currentIndexChanged, this, [this, templates, newColonies] {
        const auto planned = planned_production_state(state_, pendingOrders_);
        const auto* player = find_player(planned, pendingOrders_.player);
        const auto name = templates->currentText().toStdString();
        if (player) for (const auto& value : player->productionTemplates)
            if (value.name == name) { newColonies->setChecked(value.defaultForNewColonies); break; }
    });
    connect(templates, &QComboBox::editTextChanged, this, [this] { refreshProductionQueue(); });

    productionQueueSummary_ = new QLabel(group);
    productionQueueSummary_->setWordWrap(true);
    layout->addWidget(productionQueueSummary_);

    productionQueueTree_ = new QTreeWidget(group);
    productionQueueTree_->setObjectName("productionQueueTree");
    productionQueueTree_->setColumnCount(4);
    productionQueueTree_->setHeaderLabels({"#", "Item", "Remaining", "Completion"});
    productionQueueTree_->setRootIsDecorated(false);
    productionQueueTree_->setAlternatingRowColors(true);
    productionQueueTree_->setSelectionMode(QAbstractItemView::SingleSelection);
    productionQueueTree_->setMinimumHeight(72);
    productionQueueTree_->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Ignored);
    productionQueueTree_->header()->setSectionResizeMode(0, QHeaderView::ResizeToContents);
    productionQueueTree_->header()->setSectionResizeMode(1, QHeaderView::Stretch);
    productionQueueTree_->header()->setSectionResizeMode(2, QHeaderView::ResizeToContents);
    productionQueueTree_->header()->setSectionResizeMode(3, QHeaderView::ResizeToContents);
    layout->addWidget(productionQueueTree_, 1);
    productionMineralDetails_ = new QLabel(group);
    productionMineralDetails_->setObjectName("productionMineralDetails");
    productionMineralDetails_->setTextFormat(Qt::PlainText);
    productionMineralDetails_->setWordWrap(true);
    layout->addWidget(productionMineralDetails_);

    auto* moveRow = new QHBoxLayout;
    productionMoveUpButton_ = new QPushButton("Move up", group);
    productionMoveDownButton_ = new QPushButton("Move down", group);
    productionRemoveButton_ = new QPushButton("Remove", group);
    productionRemoveButton_->setObjectName("productionRemoveButton");
    productionRemoveButton_->setToolTip("Remove the selected build (Delete). Production already spent is lost; minerals are charged only on completion.");
    productionMoveUpButton_->setToolTip("Move the selected item one position earlier");
    productionMoveDownButton_->setToolTip("Move the selected item one position later");
    moveRow->addWidget(productionMoveUpButton_);
    moveRow->addWidget(productionMoveDownButton_);
    moveRow->addWidget(productionRemoveButton_);
    layout->addLayout(moveRow);
    panelLayout->addWidget(group);

    connect(productionMoveUpButton_, &QPushButton::clicked, this,
        [this] { moveSelectedProductionItem(-1); });
    connect(productionMoveDownButton_, &QPushButton::clicked, this,
        [this] { moveSelectedProductionItem(1); });
    connect(productionRemoveButton_, &QPushButton::clicked, this, &MainWindow::removeSelectedProductionItem);
    auto* removeShortcut = new QShortcut(QKeySequence(Qt::Key_Delete), productionQueueTree_);
    removeShortcut->setContext(Qt::WidgetWithChildrenShortcut);
    connect(removeShortcut, &QShortcut::activated, this, &MainWindow::removeSelectedProductionItem);
    connect(productionQueueTree_, &QTreeWidget::itemSelectionChanged, this, [this] {
        const auto row = productionQueueTree_->indexOfTopLevelItem(productionQueueTree_->currentItem());
        productionMineralDetails_->setText(row >= 0
            ? productionQueueTree_->currentItem()->data(0, Qt::UserRole + 1).toString() : QString{});
        productionMoveUpButton_->setEnabled(row > 0);
        productionRemoveButton_->setEnabled(row >= 0);
        productionMoveDownButton_->setEnabled(
            row >= 0 && row + 1 < productionQueueTree_->topLevelItemCount());
    });

    auto* timer = new QTimer(this);
    timer->setInterval(150);
    connect(timer, &QTimer::timeout, this, &MainWindow::refreshProductionQueue);
    timer->start();
    refreshProductionQueue();
}

void MainWindow::refreshProductionQueue()
{
    if (shuttingDown_ || !productionQueueTree_ || !productionQueueSummary_) return;
    const auto previousRow = productionQueueTree_->indexOfTopLevelItem(productionQueueTree_->currentItem());
    const auto previousPlanet = productionQueuePlanet_;
    const auto previousScroll = productionQueueTree_->verticalScrollBar()->value();
    productionQueueTree_->clear();
    productionMineralDetails_->clear();
    productionQueuePlanet_.reset();
    auto* batchKind = findChild<QComboBox*>("productionBatchKind");
    auto* batchAdd = findChild<QPushButton*>("productionBatchAdd");
    auto* templateName = findChild<QComboBox*>("productionTemplateName");
    auto* templateSave = findChild<QPushButton*>("productionTemplateSave");
    auto* templateApply = findChild<QPushButton*>("productionTemplateApply");
    auto* templateDelete = findChild<QPushButton*>("productionTemplateDelete");
    batchAdd->setEnabled(false); templateSave->setEnabled(false); templateApply->setEnabled(false); templateDelete->setEnabled(false);

    const auto* planet = selectedPlanet();
    if (!planet || planet->owner != pendingOrders_.player) {
        productionQueueSummary_->setText("Select a friendly colony to inspect its production plan.");
        productionQueueSummary_->setToolTip({});
        if (auto* details = findChild<QLabel*>("productionExtendedSummary")) details->setText(productionQueueSummary_->text());
        productionMoveUpButton_->setEnabled(false);
        productionMoveDownButton_->setEnabled(false);
        productionRemoveButton_->setEnabled(false);
        return;
    }

    productionQueuePlanet_ = planet->id;
    auto forecastState = planned_production_state(state_, pendingOrders_);
    const auto projectedPlanet = std::find_if(forecastState.planets.begin(), forecastState.planets.end(),
        [planet](const auto& candidate) { return candidate.id == planet->id; });
    const auto queue = projectedPlanet->productionQueue;
    const auto forecastPlayerIt = std::find_if(
        forecastState.players.begin(), forecastState.players.end(), [this](const Player& player) {
            return player.id == pendingOrders_.player;
        });
    auto* forecastPlayer = forecastPlayerIt == forecastState.players.end() ? nullptr : &*forecastPlayerIt;
    if (forecastPlayer) {
        for (const auto& order : pendingOrders_.orders) {
            if (const auto* allocation = std::get_if<SetResearchAllocationOrder>(&order)) {
                forecastPlayer->technology.researchAllocationPercent = allocation->percent;
            } else if (const auto* plan = std::get_if<SetResearchPlanOrder>(&order)) {
                forecastPlayer->technology.researchActive = plan->active;
            }
        }
    }
    if (forecastPlayer) {
        QStringList names;
        for (const auto& value : forecastPlayer->productionTemplates) names << QString::fromStdString(value.name);
        if (templateName->property("templateNames").toStringList() != names) {
            const QSignalBlocker block(templateName);
            const auto name = templateName->currentText();
            templateName->clear(); templateName->addItems(names); templateName->setEditText(name);
            templateName->setProperty("templateNames", names);
        }
        const auto name = templateName->currentText().trimmed().toStdString();
        const bool exists = std::any_of(forecastPlayer->productionTemplates.begin(), forecastPlayer->productionTemplates.end(),
            [&](const auto& value) { return value.name == name; });
        templateApply->setEnabled(exists); templateDelete->setEnabled(exists);
        templateSave->setEnabled(!name.empty() && std::any_of(queue.begin(), queue.end(),
            [](const auto& item) { return item.automation != ProductionAutomation::None; }));
    }
    batchAdd->setEnabled(batchKind->currentData().toInt() != int(ProductionKind::Terraforming)
        || next_terraforming_environment(forecastState, pendingOrders_.player, *planet).has_value());
    const auto forecast = forecast_production_queue(forecastState, *planet, queue);
    const auto allocationPercent = forecastPlayer && forecastPlayer->technology.researchActive
        ? forecastPlayer->technology.researchAllocationPercent
        : 0;
    const auto output = colony_output(*planet);
    const auto guaranteedResearch = static_cast<std::uint32_t>(
        static_cast<std::uint64_t>(output) * allocationPercent / 100U);
    productionQueueSummary_->setText(
        QString("<b>%1</b> • output %2/turn • guaranteed research %3 • production %4 • %5 item%6")
            .arg(QString::fromStdString(planet->name))
            .arg(output)
            .arg(guaranteedResearch)
            .arg(output - guaranteedResearch)
            .arg(static_cast<qulonglong>(queue.size()))
            .arg(queue.size() == 1 ? "" : "s"));

    MineralCargo total;
    for (std::size_t index = 0; index < queue.size(); ++index) {
        const auto& item = queue[index];
        auto units = item.quantity;
        if (item.automation != ProductionAutomation::None && index > 0
            && queue[index - 1].autoGenerated && queue[index - 1].kind == item.kind) --units;
        const auto cost = production_item_mineral_cost(forecastState, item);
        total.ironium += cost.ironium * units;
        total.boranium += cost.boranium * units;
        total.germanium += cost.germanium * units;
    }
    productionQueueSummary_->setText(productionQueueSummary_->text()
        + QString("<br>Stock: %1<br>Mining/turn: %2<br>Queue minerals (auto rules: one annual limit): %3<br>Minerals are spent on completion.")
            .arg(mineralAmounts(planet->minerals), mineralAmounts(projected_mineral_mining(state_, *planet)), mineralAmounts(total)));
    const auto fullSummary = productionQueueSummary_->text();
    if (auto* details = findChild<QLabel*>("productionExtendedSummary")) details->setText(fullSummary);
    if (productionQueueSummary_->property("compactColonySummary").toBool()) {
        productionQueueSummary_->setToolTip(fullSummary);
        productionQueueSummary_->setText(QString("Production %1 / year • Research %2<br>%3 item%4%5")
            .arg(output - guaranteedResearch).arg(guaranteedResearch)
            .arg(queue.size()).arg(queue.size() == 1 ? "" : "s").arg(queue.empty() ? " — queue empty" : ""));
    }

    bool shipyardAvailable = colony_has_orbital_service(
        state_, planet->id, planet->owner, OrbitalStationModule::Shipyard);
    for (std::size_t index = 0; index < queue.size(); ++index) {
        const auto& item = queue[index];
        const bool automatic = item.automation != ProductionAutomation::None;
        QString remaining = automatic ? QString("≤%1/yr").arg(item.quantity)
            : QString::number(item.remainingCost + (item.quantity - 1) * production_item_cost(forecastState, item));
        const bool waitingForShipyard = item.kind == ProductionKind::ColonyShip
            && !shipyardAvailable;
        if (waitingForShipyard) {
            remaining = "shipyard";
        } else if (item.remainingCost == 0
            && !mineral_cargo_sufficient(planet->minerals, production_item_mineral_cost(forecastState, item))) {
            remaining = "minerals";
        }

        QString completion;
        if (forecast[index].completionTurn) {
            completion = QString("Turn %1 (+%2)")
                .arg(static_cast<qulonglong>(*forecast[index].completionTurn))
                .arg(static_cast<qulonglong>(*forecast[index].completionTurn - state_.turn));
        } else completion = waitingForShipyard ? "waiting for dock" : "beyond forecast";
        if (automatic) completion = forecast[index].completionTurn
            ? QString("First +%1 yr").arg(*forecast[index].completionTurn - state_.turn)
            : "Idle / beyond forecast";

        auto* row = new QTreeWidgetItem(productionQueueTree_);
        row->setText(0, QString::number(index + 1));
        row->setText(1, productionItemName(forecastState, item));
        row->setText(2, remaining);
        row->setText(3, completion);
        if (automatic) { auto font = row->font(1); font.setItalic(true); row->setFont(1, font); }
        row->setData(0, Qt::UserRole, static_cast<qulonglong>(index));
        const auto cost = production_item_mineral_cost(forecastState, item);
        const MineralCargo missing{std::max(0.0, cost.ironium - planet->minerals.ironium),
            std::max(0.0, cost.boranium - planet->minerals.boranium),
            std::max(0.0, cost.germanium - planet->minerals.germanium)};
        auto details = QString("%1 — minerals per completed unit: %2\n"
                                     "Shortfall against current stock before other builds: %3")
            .arg(productionItemName(forecastState, item), mineralAmounts(cost), mineralAmounts(missing));
        if (automatic) {
            details += QString("\nPersistent rule: up to %1 units each year; queue priority applies. Impossible work is skipped. First-completion estimate assumes current technology; forecast horizon is 256 years.").arg(item.quantity);
            if (forecast[index].completionTurn) details += QString("\nFirst completion: Turn %1").arg(*forecast[index].completionTurn);
        }
        if (item.kind == ProductionKind::Terraforming) details += QString("\nEach unit costs %1 production and shifts one physical axis by 1 point. Hab improvement may differ.").arg(kTerraformingCost);
        row->setData(0, Qt::UserRole + 1, details);
        for (int column = 0; column < 4; ++column) row->setToolTip(column, details);
        if (item.kind == ProductionKind::OrbitalStation) shipyardAvailable = true;
    }

    if (!queue.empty()) {
        const auto selectedRow = previousPlanet == planet->id
            ? std::clamp(previousRow, 0, static_cast<int>(queue.size() - 1)) : 0;
        productionQueueTree_->setCurrentItem(productionQueueTree_->topLevelItem(selectedRow));
    }
    productionQueueTree_->doItemsLayout();
    productionQueueTree_->verticalScrollBar()->setValue(previousPlanet == planet->id ? previousScroll : 0);
    const auto row = productionQueueTree_->indexOfTopLevelItem(productionQueueTree_->currentItem());
    productionMoveUpButton_->setEnabled(row > 0);
    productionMoveDownButton_->setEnabled(row >= 0 && row + 1 < static_cast<int>(queue.size()));
    productionRemoveButton_->setEnabled(row >= 0);
}

void MainWindow::removeSelectedProductionItem()
{
    const auto* planet = selectedPlanet();
    if (!planet || planet->owner != pendingOrders_.player || !productionQueueTree_
        || productionQueuePlanet_ != planet->id) return;
    const auto row = productionQueueTree_->indexOfTopLevelItem(productionQueueTree_->currentItem());
    if (row < 0) return;
    const auto queue = plannedProductionQueue(*planet);
    if (static_cast<std::size_t>(row) >= queue.size()) return;
    appendPendingOrder(
        CancelProductionOrder{planet->id, static_cast<std::uint32_t>(row)},
        QString("Cancel %1 at %2")
            .arg(productionItemName(planned_ship_design_state(state_, pendingOrders_), queue[row]))
            .arg(QString::fromStdString(planet->name)));
    refreshProductionQueue();
}

void MainWindow::moveSelectedProductionItem(int direction)
{
    const auto* planet = selectedPlanet();
    if (!planet || planet->owner != pendingOrders_.player || !productionQueueTree_
        || productionQueuePlanet_ != planet->id) return;
    const auto from = productionQueueTree_->indexOfTopLevelItem(productionQueueTree_->currentItem());
    const auto to = from + direction;
    if (from < 0 || to < 0 || to >= productionQueueTree_->topLevelItemCount()) return;

    const auto itemName = productionQueueTree_->topLevelItem(from)->text(1);
    appendPendingOrder(
        ReorderProductionQueueOrder{
            planet->id,
            static_cast<std::uint32_t>(from),
            static_cast<std::uint32_t>(to),
        },
        QString("Move %1 to production position %2 at %3")
            .arg(itemName)
            .arg(to + 1)
            .arg(QString::fromStdString(planet->name)));
    refreshProductionQueue();
    productionQueueTree_->setCurrentItem(productionQueueTree_->topLevelItem(to));
}

} // namespace suns
