name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linux:
    runs-on: [self-hosted, Linux, X64, suns]
    steps:
      - uses: actions/checkout@v4
      - name: Toolchain info
        run: |
          cmake --version
          ninja --version
          g++ --version
          qmake6 --version
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
